# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
    volumes:
      - ./datadir:/data/db
    ports:
      - 27017:27017
  
# frontend:

  backend:
   image: backend
   build: ./backend
   ports:
    - 6001:6001
   depends_on:
    - mongo

  tasks:
   image: tasks
   build:
    context: ./backend
    dockerfile: Dockerfile-tasks
   depends_on:
    - mongo
    - backend